### PR TITLE
Fix Unit Test and migrate to yarn

### PR DESCRIPTION
**Pull request by heralight**
Hello,

A quick pull to fix unit test, migrate to yarn and update jasmine dependencies.
I use  typescrypt fix  from  angular/angular-cli#2206 probably not the right solution.

best regards and good job on fireloop!

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
Hey @heralight thanks for contributing.

What are your thoughts on this: create yarn_setup command for people that uses yarn and leave setup for the people that still uses npm?.

I like the idea of yarn, and people is starting to use but from the experience I know this will lead to new issues from people trying to install using npm.

maybe installing yarn locally to avoid missing command issues? if that is the case then creating new scripts won't be necessary. otherwise also adding the yarn_setup command within the readme would be a good idea for people using yarn.

**Comment by heralight** [comment]
@jonathan-casarrubias , yes, it's a good idea to do some separation between npm and yarn.
To simplify typing what do you think to shortcut it to "ylint", "ystart", "ysetup",... etc ?

**Comment by jonathan-casarrubias** [comment]
@heralight yes actually I like that idea, if you can add that to the readme so yarn users know how to setup.

I really appreciate your contribution.

Cheers
jon

**Comment by heralight** [comment]
I made a rollback on package.json to npm, add a ysetup and add yarn documentation.
I only fix npm test on webapp not on root.

**Comment by jonathan-casarrubias** [comment]
Hey @heralight thanks a lot for your contribution and I hope to keep seeing you around

cheers
jon

**Pull request merged**
